/**
 * Content layer: bundled exams under /content (generated by
 * scripts/build-site-content.mjs) plus user-imported exams/blobs in
 * IndexedDB. Mirrors what the desktop `library.rs` + `resolve_asset`
 * pair does with the filesystem.
 */
import { idbGet, idbKeys, idbSet } from "./idb";
import type { AudioStatus, Exam, ExamSummary, Transcript } from "./types";

export interface ExamMeta {
  /** 高频/中频/低频/常规 — from site/content-meta.json curation, never invented. */
  frequency?: "high" | "mid" | "low" | "normal";
  difficulty?: "easy" | "medium" | "hard";
  season?: string;
  tags?: string[];
  featured?: boolean;
  note?: string;
}

export interface IndexedExam extends ExamSummary {
  book?: number;
  test?: number;
  partLabels?: string[];
  questionTypes?: string[];
  /** Listening: the audioAsset paths this paper needs (index-time copy). */
  audioAssets?: string[];
  meta?: ExamMeta;
}

export interface ContentIndex {
  generatedAt: string;
  exams: IndexedExam[];
}

let indexCache: Promise<ContentIndex> | null = null;

async function fetchIndex(): Promise<ContentIndex> {
  const res = await fetch("/content/index.json");
  if (!res.ok) throw new Error(`题库索引加载失败 (${res.status})`);
  const bundled = (await res.json()) as ContentIndex;
  // Index rows are built offline, so listening audioStatus is always "missing"
  // there — recompute it against the blobs the user actually imported.
  const blobSet = new Set(await idbKeys("blobs"));
  const exams = bundled.exams.map((e) => {
    if (e.module !== "listening" || e.audioStatus === "ready") return e;
    const ready = (e.audioAssets ?? []).some((rel) => blobSet.has(rel.replace(/^\/+/, "")));
    return { ...e, audioStatus: (ready ? "ready" : "missing") as AudioStatus };
  });
  const imported = await importedExamSummaries();
  return {
    generatedAt: bundled.generatedAt,
    exams: [...imported, ...exams],
  };
}

export function invalidateContentIndex() {
  indexCache = null;
}

export function contentIndex(): Promise<ContentIndex> {
  if (!indexCache) indexCache = fetchIndex();
  return indexCache;
}

async function importedExamSummaries(): Promise<IndexedExam[]> {
  const ids = await idbKeys("exams");
  const out: IndexedExam[] = [];
  for (const id of ids) {
    const exam = await idbGet<Exam>("exams", id);
    if (!exam) continue;
    out.push({
      id: exam.id,
      title: exam.title,
      module: exam.module,
      source: exam.source,
      path: `idb:${exam.id}`,
      questionCount: exam.sections.reduce(
        (n, s) => n + s.questionGroups.reduce((m, g) => m + g.questions.length, 0),
        0,
      ),
      hasTranscript: Boolean(await idbGet("transcripts", exam.id)),
      audioStatus: await audioStatusFor(exam),
      partLabels: exam.sections.map((s) => s.title),
      questionTypes: [
        ...new Set(
          exam.sections.flatMap((s) => s.questionGroups.map((g) => g.questionType)),
        ),
      ],
    });
  }
  return out;
}

/** Imported exams win over bundled ones with the same id. */
export async function loadExam(id: string): Promise<Exam> {
  const imported = await idbGet<Exam>("exams", id);
  if (imported) return imported;
  const res = await fetch(`/content/exams/${encodeURIComponent(id)}.json`);
  if (!res.ok) throw new Error(`试卷不存在或加载失败: ${id}`);
  return (await res.json()) as Exam;
}

export async function saveImportedExam(exam: Exam): Promise<void> {
  await idbSet("exams", exam.id, exam);
  invalidateContentIndex();
}

export async function loadTranscript(examId: string): Promise<Transcript | null> {
  const imported = await idbGet<Transcript>("transcripts", examId);
  if (imported) return imported;
  const res = await fetch(`/content/transcripts/${encodeURIComponent(examId)}.json`);
  if (!res.ok) return null;
  try {
    return (await res.json()) as Transcript;
  } catch {
    return null;
  }
}

const SAFE_REL = /^[A-Za-z0-9_\-./]+$/;
const blobUrls = new Map<string, string>();

/**
 * Resolve an asset path like `assets/cambridge/c10-t1.mp3`.
 * User-imported blobs (IndexedDB) win; otherwise fall back to the bundled
 * /content directory. Returns null when nothing exists — callers render the
 * "audio missing" state rather than a broken player.
 */
export async function assetSrc(rel: string): Promise<string | null> {
  const clean = rel.replace(/^\/+/, "");
  if (!SAFE_REL.test(clean) || clean.includes("..")) return null;
  const blob = await idbGet<Blob>("blobs", clean);
  if (blob) {
    let url = blobUrls.get(clean);
    if (!url) {
      url = URL.createObjectURL(blob);
      blobUrls.set(clean, url);
    }
    return url;
  }
  return `/content/${clean}`;
}

/** True when the asset only exists as a bundled path (or nothing at all). */
export async function blobExists(rel: string): Promise<boolean> {
  const clean = rel.replace(/^\/+/, "");
  return Boolean(await idbGet<Blob>("blobs", clean));
}

export async function saveBlob(rel: string, blob: Blob): Promise<void> {
  const clean = rel.replace(/^\/+/, "");
  if (!SAFE_REL.test(clean) || clean.includes("..")) throw new Error("非法资源路径");
  await idbSet("blobs", clean, blob);
  const old = blobUrls.get(clean);
  if (old) {
    URL.revokeObjectURL(old);
    blobUrls.delete(clean);
  }
}

export async function audioStatusFor(exam: Exam): Promise<AudioStatus> {
  if (exam.module !== "listening") return "ready";
  const assets = exam.sections.map((s) => s.audioAsset).filter(Boolean) as string[];
  if (assets.length === 0) return "missing";
  for (const rel of new Set(assets)) {
    if (await blobExists(rel)) return "ready";
  }
  return "missing";
}

export interface WebPlaybackSource {
  examId: string;
  /** Object URL for the imported audio blob. */
  src: string;
  /** Per-section start offsets into the concatenated track. */
  partStartsMs: number[];
}

/**
 * Listening playback needs the concatenated per-test MP3 the exam JSON points
 * at (`section.audioAsset`). Sections carry audioStartMs/audioDurationMs so
 * part navigation is just seeking inside one file — same as desktop.
 */
export async function playbackSourceFor(exam: Exam): Promise<WebPlaybackSource | null> {
  const rel = exam.sections.find((s) => s.audioAsset)?.audioAsset;
  if (!rel) return null;
  const clean = rel.replace(/^\/+/, "");
  const blob = await idbGet<Blob>("blobs", clean);
  if (!blob) return null;
  let url = blobUrls.get(clean);
  if (!url) {
    url = URL.createObjectURL(blob);
    blobUrls.set(clean, url);
  }
  return {
    examId: exam.id,
    src: url,
    partStartsMs: exam.sections.map((s) => s.audioStartMs ?? 0),
  };
}
